# Generated by Django 4.2.2 on 2023-10-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trolleybus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trolleybus_number", models.PositiveIntegerField()),
                ("route_number", models.PositiveIntegerField()),
                ("capacity", models.PositiveIntegerField()),
                ("max_speed", models.PositiveIntegerField()),
            ],
        ),
    ]
